# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: Spark ClickHouse Connector
site_author: Cheng Pan
repo_name: housepower/spark-clickhouse-connector
repo_url: https://github.com/housepower/spark-clickhouse-connector

plugins:
  - search
  - macros

theme:
  name: material
  language: en
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra:
  version: 0.5.0
  stable_version: 0.5.0
  clickhouse_version: 22.3.3.44
  clickhouse_jdbc_version: 0.3.2-patch11
  scala_binary_version: 2.12
  spark_binary_version: 3.3
  spark_version: 3.3.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pan3793

nav:
  - Home: index.md
  - Quick Start:
    - Get the Library: quick_start/01_get_the_library.md
    - Play with Spark SQL: quick_start/02_play_with_spark_sql.md
    - Play with Spark Shell: quick_start/03_play_with_spark_shell.md
  - Best Practices:
    - Deployment: best_practices/01_deployment.md
  - Configurations:
    - configurations/index.md
    - Catalog Configurations: configurations/01_catalog_configurations.md
    - SQL Configurations: configurations/02_sql_configurations.md
  - Developers:
    - Build and Test: developers/01_build_and_test.md
    - Docs and Website: developers/02_docs_and_website.md
    - Private Release: developers/03_private_release.md
    - Public Release: developers/04_public_release.md
  - Internals:
    - internals/index.md
    - Catalog: internals/01_catalog.md
    - Reading: internals/02_read.md
    - Writing: internals/03_write.md
